CREATE DATABASE BUSINESS2_1;

USE BUSINESS2_1;

CREATE TABLE CLIENT(
      IDCLIENT INT PRIMARY KEY AUTO_INCREMENT,
      NAME VARCHAR(100) NOT NULL,
      GENDER ENUM("M", "F") NOT NULL,
      EMAIL VARCHAR(100) UNIQUE,
      CPF VARCHAR(15) UNIQUE
);

CREATE TABLE ADDRESS(
      IDADRESS INT PRIMARY KEY AUTO_INCREMENT,
      ST VARCHAR(100) NOT NULL,
      DISTRICT VARCHAR(100) NOT NULL,
      CITY VARCHAR(100) NOT NULL,
      STATE CHAR(2) NOT NULL,
      F_IDCLIENT INT UNIQUE,

      FOREIGN KEY(F_IDCLIENT)
      REFERENCES CLIENT(IDCLIENT)
);

CREATE TABLE PHONE (
      IDPHONE INT PRIMARY KEY AUTO_INCREMENT,
      TYPE ENUM("RES","COM","CEL") NOT NULL,
      NUMBER VARCHAR(10) NOT NULL,
      F_IDCLIENT INT,

      FOREIGN KEY (F_IDCLIENT)
      REFERENCES CLIENT(IDCLIENT)
);

DROP TABLE CLIENT;
DROP TABLE ADDRESS;
DROP TABLE PHONE;

-- 1
INSERT INTO CLIENT VALUES(NULL,'FLAVIO','M','FLAVIO@IG.COM','4657765');
INSERT INTO CLIENT VALUES(NULL,'ANDRE','M','ANDRE@GLOBO.COM','7687567');
INSERT INTO CLIENT VALUES(NULL,'GIOVANA','F',NULL,'0876655');
INSERT INTO CLIENT VALUES(NULL,'KARLA','M','KARLA@GMAIL.COM','545676778');
INSERT INTO CLIENT VALUES(NULL,'DANIELE','M','DANIELE@GMAIL.COM','43536789');
INSERT INTO CLIENT VALUES(NULL,'LORENA','M',NULL,'774557887');
INSERT INTO CLIENT VALUES(NULL,'EDUARDO','M',NULL,'54376457');
INSERT INTO CLIENT VALUES(NULL,'ANTONIO','F','ANTONIO@IG.COM','12436767');
INSERT INTO CLIENT VALUES(NULL,'ANTONIO','M','ANTONIO@UOL.COM','3423565');
INSERT INTO CLIENT VALUES(NULL,'ELAINE','M','ELAINE@GLOBO.COM','32567763');
INSERT INTO CLIENT VALUES(NULL,'CARMEM','M','CARMEM@IG.COM','787832213');
INSERT INTO CLIENT VALUES(NULL,'ADRIANA','F','ADRIANA@GMAIL.COM','88556942');
INSERT INTO CLIENT VALUES(NULL,'LEANDRO','F','LEO@GMAIL.COM','176276176');
INSERT INTO CLIENT VALUES(NULL,'JORGE','F','JORGE@GMAIL.COM','129818291');
INSERT INTO CLIENT VALUES(NULL,'GIOVANA','F','GIO@GMAIL.COM','12189892');
INSERT INTO CLIENT VALUES(NULL,'SILVANA','F','SILVANA@GMAIL.COM','271676111');
INSERT INTO CLIENT VALUES(NULL,'GLAUCIANE','F','GLAUC@GMAIL.COM','9898393');
INSERT INTO CLIENT VALUES(NULL,'CASSANDRA','F','CASSIA@GMAIL.COM','2392889');
INSERT INTO CLIENT VALUES(NULL,'JENILDA','F','JENILDA@GMAIL.COM','1982911');
INSERT INTO CLIENT VALUES(NULL,'JUCELINO','F','JUCELINO@GMAIL.COM','52939289');
INSERT INTO CLIENT VALUES(NULL,'JOÃO','M','JOAO@GMAIL.COM','2392899');

-- 2
INSERT INTO ADDRESS VALUES(NULL,'RUA GUEDES','CASCADURA','B. HORIZONTE','MG',9);
INSERT INTO ADDRESS VALUES(NULL,'RUA MAIA LACERDA','ESTACIO','RIO DE JANEIRO','RJ',10);
INSERT INTO ADDRESS VALUES(NULL,'RUA VISCONDESSA','CENTRO','RIO DE JANEIRO','RJ',11);
INSERT INTO ADDRESS VALUES(NULL,'RUA NELSON MANDELA','COPACABANA','RIO DE JANEIRO','RJ',12);
INSERT INTO ADDRESS VALUES(NULL,'RUA ARAUJO LIMA','CENTRO','VITORIA','ES',13);
INSERT INTO ADDRESS VALUES(NULL,'RUA CASTRO ALVES','LEBLON','RIO DE JANEIRO','RJ',14);
INSERT INTO ADDRESS VALUES(NULL,'AV CAPITAO ANTUNES','CENTRO','CURITIBA','PR',15);
INSERT INTO ADDRESS VALUES(NULL,'AV CARLOS BARROSO','JARDINS','SAO PAULO','SP',16);
INSERT INTO ADDRESS VALUES(NULL,'ALAMEDA SAMPAIO','BOM RETIRO','CURITIBA','PR',17);
INSERT INTO ADDRESS VALUES(NULL,'RUA DA LAPA','LAPA','SAO PAULO','SP',18);
INSERT INTO ADDRESS VALUES(NULL,'RUA GERONIMO','CENTRO','RIO DE JANEIRO','RJ',19);
INSERT INTO ADDRESS VALUES(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',20);
INSERT INTO ADDRESS VALUES(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',21);

-- 3
INSERT INTO PHONE VALUES(NULL,'RES','68976565',9);
INSERT INTO PHONE VALUES(NULL,'CEL','99656675',9);
INSERT INTO PHONE VALUES(NULL,'CEL','33567765',11);
INSERT INTO PHONE VALUES(NULL,'CEL','88668786',11);
INSERT INTO PHONE VALUES(NULL,'COM','55689654',11);
INSERT INTO PHONE VALUES(NULL,'COM','88687979',12);
INSERT INTO PHONE VALUES(NULL,'COM','88965676',13);
INSERT INTO PHONE VALUES(NULL,'CEL','89966809',15);
INSERT INTO PHONE VALUES(NULL,'COM','88679978',16);
INSERT INTO PHONE VALUES(NULL,'CEL','99655768',17);
INSERT INTO PHONE VALUES(NULL,'RES','89955665',18);
INSERT INTO PHONE VALUES(NULL,'RES','77455786',19);
INSERT INTO PHONE VALUES(NULL,'RES','89766554',19);
INSERT INTO PHONE VALUES(NULL,'RES','77755785',20);
INSERT INTO PHONE VALUES(NULL,'COM','44522578',20);

-- 4
SELECT * FROM CLIENT;

DESC CLIENTE;
DESC ADDRESS;
DESC PHONE;

-- 5
SELECT * FROM ADDRESS;
SELECT * FROM PHONE;

SELECT C.IDCLIENT, C.NAME, C.GENDER, C.EMAIL, C.CPF, 
      A.ST, A.DISTRICT, A.CITY, A.STATE,
            P.TYPE, P.NUMBER
FROM CLIENT C
INNER JOIN PHONE P
ON C.IDCLIENT=P.F_IDCLIENT
INNER JOIN ADDRESS A 
ON C.IDCLIENT=A.F_IDCLIENT;

-- 6
SELECT C.IDCLIENT, C.NAME, C.GENDER, C.EMAIL, C.CPF,
            A.ST, A.DISTRICT, A.CITY, A.STATE, 
                  P.TYPE, P.NUMBER
FROM CLIENT C
INNER JOIN PHONE P
ON C.IDCLIENT=P.F_IDCLIENT
INNER JOIN ADDRESS A 
ON C.IDCLIENT=A.F_IDCLIENT
WHERE C.GENDER="M";

-- 7 -> IN
SELECT * FROM CLIENT
WHERE IDCLIENT IN (12, 13,18, 19);

UPDATE CLIENT
SET GENDER="M"
WHERE IDCLIENT IN (5, 6, 10, 11,4);

-- 8
SELECT C.IDCLIENT, C.NAME, C.GENDER, C.EMAIL, C.CPF, 
            A.ST, A.DISTRICT, A.CITY, A.STATE, 
                  P.TYPE, P.NUMBER
FROM CLIENT C 
INNER JOIN PHONE P 
ON C.IDCLIENT=P.F_IDCLIENT
INNER JOIN ADDRESS A 
ON C.IDCLIENT=A.F_IDCLIENT
WHERE C.GENDER="F";

-- 9
SELECT C.GENDER, COUNT(*) AS "M E F"
FROM CLIENT C 
GROUP BY GENDER;


-- 10
SELECT C.IDCLIENT, C.EMAIL, C.GENDER, 
            A.DISTRICT, A.CITY, 
                  P.TYPE, P.NUMBER
FROM CLIENT C 
INNER JOIN ADDRESS A 
ON C.IDCLIENT=A.F_IDCLIENT
INNER JOIN PHONE P 
ON C.IDCLIENT=P.F_IDCLIENT
WHERE C.GENDER="F" 
AND A.DISTRICT="CENTRO"
AND (P.TYPE="RES" OR P.TYPE="COM");

-- 11
SELECT C.NAME, C.EMAIL, 
            P.TYPE, P.NUMBER, 
                  A.STATE
FROM CLIENT C 
INNER JOIN ADDRESS A 
ON C.IDCLIENT=A.F_IDCLIENT
INNER JOIN PHONE P
ON C.IDCLIENT=P.F_IDCLIENT
WHERE A.STATE="RJ" AND P.TYPE="CEL";

-- 12
SELECT C.NAME, C.EMAIL, C.GENDER, P.TYPE, P.NUMBER, A.STATE
FROM CLIENT C
INNER JOIN ADDRESS A 
ON C.IDCLIENT=A.F_IDCLIENT
INNER JOIN PHONE P 
ON C.IDCLIENT=P.F_IDCLIENT
WHERE C.GENDER="F" 
AND A.STATE="SP" 

