-- NAME, EMAIL, NUMBER, STATE
SELECT C.NAME, C.EMAIL, 
            P.NUMBER, 
                  A.STATE
FROM CLIENT C 
INNER JOIN ADDRESS A 
ON C.IDCLIENT=A.F_IDCLIENT
INNER JOIN PHONE P
ON C.IDCLIENT=P.F_IDCLIENT;

INSERT INTO CLIENT VALUES (NULL, "JOANA","F",NULL, 239823892);
INSERT INTO CLIENT VALUES (NULL, "ELIANA","F",NULL, 92839211);
INSERT INTO CLIENT VALUES (NULL, "JUNIOR","M",NULL, 090920901);
INSERT INTO CLIENT VALUES (NULL, "DOUGLAS","M",NULL, 1209019011);
-- IFNULL
SELECT C.NAME, IFNULL(C.EMAIL,"NÃO TEM EMAIL") AS EMAILS, 
            A.STATE, 
                  P.NUMBER 
FROM CLIENT C 
INNER JOIN ADDRESS A
ON C.IDCLIENT=A.F_IDCLIENT
INNER JOIN PHONE P 
ON C.IDCLIENT=P.F_IDCLIENT;


-- VIEW - PREFIXO VIEW_EXEMPLO
CREATE VIEW VIEW_RELAT AS
SELECT C.NAME, C.GENDER, C.EMAIL, 
            P.TYPE, P.NUMBER, 
                  A.DISTRICT, A.CITY, A.STATE
FROM CLIENT C 
INNER JOIN ADDRESS A 
ON C.IDCLIENT=A.F_IDCLIENT
INNER JOIN PHONE P 
ON C.IDCLIENT=P.F_IDCLIENT;

SELECT * FROM VIEW_RELAT;

SHOW VIEW; -- ERRADO

-- APAGANDO VIEW
DROP VIEW VIEW_RELAT;

-- QUERY
SELECT NAME, NUMBER, STATE
FROM VIEW_RELAT;

-- DML
INSERT INTO VIEW_RELAT VALUES('ANDREIA','F','ANDREIA@UOL.COM.BR','CEL','873547864','CENTRO','VITORIA','ES'); 
ERROR 1394 (HY000): Can not insert into join view 'BUSINESS2_1.VIEW_RELAT' without fields list
DELETE FROM VIEW_RELAT WHERE NAME='JORGE';
ERROR 1395 (HY000): Can not delete from join view 'BUSINESS2_1.VIEW_RELAT'
-- FORMA ERRADA ^

-- UPDATES COM JOIN
UPDATE VIEW_RELAT
SET NAME="ADRIANA" WHERE NAME="CONRAD";

CREATE TABLE PLAYERS (
      IDPLAYER INT, 
      NAME VARCHAR(100),
      STATE CHAR(2)
);


INSERT INTO PLAYERS VALUES(1,'GUERRERO','RS');
INSERT INTO PLAYERS VALUES(2,'GABIGOL','RJ');
INSERT INTO PLAYERS VALUES(3,'GANSO','RJ');
INSERT INTO PLAYERS VALUES(4,'NENÊ', 'RJ');
INSERT INTO PLAYERS VALUES(5,'LOVE','SP');

CREATE VIEW VIEW_PLAYERS AS
SELECT NAME, STATE
FROM PLAYERS;

INSERT INTO VIEW_PLAYERS VALUES("GUERRERO","RS");

SELECT * FROM VIEW_RELAT
WHERE GENDER="F";

CREATE TABLE STUDENTS (
      NUMBER INT,
      NAME VARCHAR(100)
);

-- ORDER BY
INSERT INTO STUDENTS VALUES(1,'JOAO');
INSERT INTO STUDENTS VALUES(1,'MARIA');
INSERT INTO STUDENTS VALUES(2,'ZOE');
INSERT INTO STUDENTS VALUES(2,'ANDRE');
INSERT INTO STUDENTS VALUES(3,'CLARA');
INSERT INTO STUDENTS VALUES(1,'CLARA');
INSERT INTO STUDENTS VALUES(4,'MAFRA');
INSERT INTO STUDENTS VALUES(5,'JANAINA');
INSERT INTO STUDENTS VALUES(1,'JANAINA');
INSERT INTO STUDENTS VALUES(3,'MARCELO');
INSERT INTO STUDENTS VALUES(4,'GIOVANI');
INSERT INTO STUDENTS VALUES(5,'ANTONIO');
INSERT INTO STUDENTS VALUES(6,'ANA');
INSERT INTO STUDENTS VALUES(6,'VIVIANE');

SELECT * FROM STUDENTS
ORDER BY NUMBER;

SELECT * FROM STUDENTS
ORDER BY 1;

SELECT * FROM STUDENTS
ORDER BY 2;

-- ORDENANDO MAIS DE UMA COLUNA
SELECT * FROM STUDENTS
ORDER BY NUMBER, NAME;

SELECT * FROM STUDENTS
ORDER BY 1, 2;

-- MESCLANDO COM PROJEÇÃO
SELECT NAME -- ERRADO
FROM STUDENTS
ORDER BY 1,2;

SELECT NAME
FROM STUDENTS
ORDER BY NUMBER, NAME;

-- ORDER BY ASC e  DESC
SELECT * FROM STUDENTS
ORDER BY 1 ASC;

SELECT * FROM STUDENTS
ORDER BY 1 DESC;


SELECT * FROM STUDENTS
ORDER BY 1, 2 DESC;

SELECT * FROM STUDENTS
ORDER BY 1 DESC, 2 DESC;


-- ORDERNANDO COM JOINS

SELECT C.NAME, C.GENDER, IFNULL(C.EMAIL,"NÃO TEM EMAIL") AS EMAILS, 
            P.TYPE, P.NUMBER, 
                  A.DISTRICT, A.CITY, A.STATE
FROM CLIENT C
INNER JOIN ADDRESS A 
ON C.IDCLIENT=A.F_IDCLIENT
INNER JOIN PHONE P 
ON C.IDCLIENT=P.F_IDCLIENT
ORDER BY 1;

-- COM VIEWS
SHOW TABLES;

SELECT * FROM VIEW_RELAT
ORDER BY 1;