-- ENTIDADE = TABEL
-- CAMPOS = ATRIBUTOS

CREATE DATABASE S1;

USE S1;

CREATE TABLE CLIENT (
      NAME VARCHAR(100),
      GENDER CHAR(1),
      EMAIL VARCHAR(100),
      CPF INT(11),
      PHONE VARCHAR(20),
      ADDRESS VARCHAR(100)
);

SHOW TABLES;

DESCRIBE CLIENT;

-- FORMA 1 OMISSÃO DAS COLUNS
INSERT INTO CLIENT VALUES ("JOÃO", "M", "JOAO@GMAIL.COM", 923892839,"923212111","MAIA LACERDA - ESTÁCIO - RIO DE JANEIRO - RJ");

INSERT INTO CLIENT VALUES ("CELIA", "F","CELIA@GMAIL.COM",3892839,"2129019", "RIACHUELO - CENTRO - RIO DE JANEIRO - RJ");

INSERT INTO CLIENT VALUES ("JORGE", "M", NULL, 29389289,"2121092", "OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG");


-- FORMA 2 ADICIONANDO COLUNAS
INSERT INTO CLIENT (NAME, GENDER, ADDRESS, PHONE, CPF)
VALUES ("LILIAN", "F","SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ", "23923892",38928938);

-- FORMA 3 INSERT COMPACTO
INSERT INTO CLIENT VALUES
("ANA","F", "ANA@GLOBO.COM", 29389283,"1210920190", "PRES. ANTONIO CARLOS - CENTRO - SÃO PAULO - SP"), 
("CARLA","F","CARLA@TERATI.COM.BR",29382398,"121982918","SAMUEL SILVA - CENTRO - BELO HORIZONTE - MG");


INSERT INTO CLIENT(NAME, GENDER, ADDRESS, PHONE, CPF)
VALUES ("CLARA","F","SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ","29382989",2392839);

INSERT INTO CLIENT (NAME, GENDER, ADDRESS, PHONE, CPF)
VALUES ("CLARA","F","SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ","2389283982",382738728);


-- PROJEÇÃO E JUNÇÃO
SELECT NOW() AS "DATA ATUAL", "DAN" AS ESTAGIÁRIO;


SELECT NAME AS CLIENTS, GENDER, EMAIL
FROM CLIENT;

-- FILTRANDO
SELECT NAME, GENDER
FROM CLIENT
WHERE GENDER="M";

SELECT NAME, ADDRESS
FROM CLIENT
WHERE GENDER="F";


-- OPERADOR LIKE
-- CARACTERE CORINGA % QUALQUER COISA
SELECT NAME, GENDER
FROM CLIENT
WHERE ADDRESS LIKE "%RJ";

SELECT NAME, GENDER, ADDRESS
FROM CLIENT
WHERE ADDRESS LIKE "%RJ";

SELECT NAME, GENDER, ADDRESS
FROM CLIENT
WHERE ADDRESS LIKE "OSCAR CURY%";

SELECT NAME, GENDER, ADDRESS
FROM CLIENT
WHERE ADDRESS LIKE "%CENTRO%";

