-- A39 - 40 TRIGGERS
CREATE TRIGGER NOME
BEFORE/AFTER INSERT/DELETE/UPDATE ON TABALEA
FOR EACH ROW
BEGIN

END

CREATE DATABASE BACKUPS;

USE BACKUPS;

CREATE TABLE USERS (
      IDUSER INT PRIMARY KEY AUTO_INCREMENT,
      NAME VARCHAR(100),
      LOGIN VARCHAR(100),
      PSSWD VARCHAR(100)
);

CREATE TABLE BKPUSER(
      IDBKP INT PRIMARY KEY AUTO_INCREMENT,
      IDUSER INT,
      NAME VARCHAR(100),
      LOGIN VARCHAR(100)
);

DELIMITER #

CREATE TRIGGER BKPUSER
BEFORE DELETE ON USERS
FOR EACH ROW
BEGIN
      INSERT INTO BKPUSER VALUES (NULL, OLD.IDUSER, OLD.NAME, OLD.LOGIN);
END
#

DELIMITER ;

INSERT INTO USERS VALUES(NULL,'ANDRADE','ANDRADE2009','HEXACAMPEAO');

SELECT * FROM USUARIO;

DELETE FROM USUARIO WHERE IDUSUARIO = 1;

DROP TRIGGER BKPUSER;

DELIMITER ;
-- A41 COMUNICAÇÃO ENTRE BANCOS
CREATE DATABASE STORE;

CREATE TABLE PRODUCT (
      IDPRODUCT INT PRIMARY KEY AUTO_INCREMENT,
      NAME VARCHAR(100),
      PRICE FLOAT(10,2)
);

USE BACKUPS;
CREATE TABLE BKPPRODUCT (
      IDBKP2 INT PRIMARY KEY AUTO_INCREMENT,
      IDPRODUCT INT,
      NAME VARCHAR(100),
      PRICE FLOAT(10,2)
);

USE STORE;

INSERT INTO BACKUPS.BKPPRODUCT VALUES (NULL, 1000, "TEST", 2.2);

SELECT * FROM BACKUPS.BKPPRODUCT;

DELIMITER #
CREATE TRIGGER BKPP
AFTER INSERT ON PRODUCT
FOR EACH ROW
BEGIN
      INSERT INTO BACKUPS.BKPPRODUCT VALUES (NULL, NEW.IDPRODUCT, NEW.NAME, NEW.PRICE);
END #

DELIMITER ;

INSERT INTO PRODUCT VALUES(NULL,'LIVRO MODELAGEM',50.00);
INSERT INTO PRODUCT VALUES(NULL,'LIVRO BI',80.00);
INSERT INTO PRODUCT VALUES(NULL,'LIVRO ORACLE',70.00);
INSERT INTO PRODUCT VALUES(NULL,'LIVRO SQL SERVER',100.00);
INSERT INTO PRODUCT VALUES(NULL,'LIVRO C#',100.00);

SELECT * FROM PRODUCT;

SELECT * FROM BACKUPS.BKPPRODUCT;

ALTER TABLE BACKUPS.BKPPRODUCT -- ADD ANTES DE CRIAR O TRIGGER BKPP_DEL
ADD EVENT CHAR(1);

DELIMITER #
CREATE TRIGGER BKPP_DEL
BEFORE DELETE ON PRODUCT
FOR EACH ROW
BEGIN
      INSERT INTO BACKUPS.BKPPRODUCT VALUES(NULL, OLD.IDPRODUCT, OLD.NAME, OLD.PRICE, "D");

END #

DELIMITER ;

SELECT * FROM PRODUCT;
SELECT * FROM BACKUPS.BKPPRODUCT;

DELETE FROM PRODUCT WHERE IDPRODUCT=1;

-- A43 AUDITORIA
CREATE DATABASE STORE2;

USE STORE2;

CREATE TABLE PRODUCT (
      IDPRODUCT INT PRIMARY KEY AUTO_INCREMENT,
      NAME VARCHAR(100),
      PRICE FLOAT(10,2)
);

INSERT INTO PRODUCT VALUES(NULL,'LIVRO MODELAGEM',50.00);
INSERT INTO PRODUCT VALUES(NULL,'LIVRO BI',80.00);
INSERT INTO PRODUCT VALUES(NULL,'LIVRO ORACLE',70.00);
INSERT INTO PRODUCT VALUES(NULL,'LIVRO SQL SERVER',100.00);

-- QUANDO
SELECT NOW();
-- QUEM
SELECT CURRENT_USER();


CREATE DATABASE BACKUPS2;

USE BACKUPS2;

CREATE TABLE BKP_PRODUCT(
      IDBKP INT PRIMARY KEY AUTO_INCREMENT,
      IDPRODUCT INT,
      NAME VARCHAR(100),
      ORIGINAL_PRICE FLOAT(10,2),
      ALTERED_PRICE FLOAT(10,2),
      DATA DATETIME,
      USER VARCHAR(100),
      EVENT CHAR(1)
);

USE STORE2;

DELIMITER #

CREATE TRIGGER BKPP2
AFTER UPDATE ON PRODUCT
FOR EACH ROW
BEGIN
      INSERT INTO BACKUPS2.BKP_PRODUCT VALUES(NULL, OLD.IDPRODUCT, OLD.NAME, OLD.PRICE, NEW.PRICE, NOW(), CURRENT_USER(), "U");
END #

DELIMITER ;

UPDATE PRODUCT
SET PRICE=300.23
WHERE IDPRODUCT=1;

SELECT * FROM PRODUCT;

SELECT * FROM BACKUPS2.BKP_PRODUCT;