-- IS/ IS NOT
SELECT NAME, GENDER, ADDRESS
FROM CLIENT
WHERE GENDER="F";

-- ERRADO
SELECT NAME, EMAIL 
FROM CLIENT
WHERE EMAIL=NULL;

SELECT NAME, GENDER, ADDRESS, EMAIL --OK
FROM CLIENT
WHERE EMAIL IS NULL;

SELECT NAME, ADDRESS, EMAIL
FROM CLIENT
WHERE EMAIL IS NOT NULL;

-- UPDATE
SELECT NAME,EMAIL
FROM CLIENT;

--WRONG
UPDATE CLIENT
SET EMAIL="LILIAN@GMAIL.COM";

SELECT NAME, EMAIL
FROM CLIENT;

UPDATE CLIENT
SET EMAIL="JOAO@GMAIL.COM"
WHERE NAME="JOÃO";

UPDATE CLIENT
SET EMAIL="CELIA@GLOBO.COM.BR"
WHERE NAME="CELIA";

UPDATE CLIENT
SET EMAIL="JORGE@HOTMAIL.COM"
WHERE NAME="JORGE";

UPDATE CLIENT
SET EMAIL="ANA@OUTLOOK.COM"
WHERE NAME="ANA";

-- CLARA ONE
UPDATE CLIENT
SET NAME="CLARA ONE"
WHERE CPF=29382398;

UPDATE CLIENT
SET EMAIL="CNE@GMAIL.COM"
WHERE NAME="CLARA ONE";

-- CLARA TWO
UPDATE CLIENT
SET NAME="CLARA TWO"
WHERE CPF =2392839;

UPDATE CLIENT
SET EMAIL="CWO@HOTMAIL.COM"
WHERE NAME="CLARA TWO";

-- CLARA THREE
UPDATE CLIENT
SET NAME="CLARA THREE"
WHERE CPF=382738728;

UPDATE CLIENT 
SET EMAIL="CTH@GMAIL.COM"
WHERE NAME="CLARA THREE";

-- CLAÚSULA DELETE
INSERT INTO CLIENT
VALUES ("CARLA FOUR", "F","CARF@UOL.COM",39283928,"83928-2329", "RUA COPPER LEAF - WILLIAMSBURG - KITCHENER");

INSERT INTO CLIENT
VALUES ("CARLA FIVE", "F","LILIAN@UOL.COM",39283928,"83928-2329", "RUA COPPER LEAF - WILLIAMSBURG - KITCHENER");

SELECT * FROM CLIENT;
-- OR TRAZ TODO MUNDO COM PELO MENOS UMA DAS DUAS CONDICOES
SELECT * FROM CLIENT
WHERE NAME="CARLA FIVE"
OR EMAIL="LILIAN@HOTMAIL.COM";

-- TRAZ APENAS O REGISTRO QUE SATISFACA AS DUAS CONDICOES
DELETE FROM CLIENT
WHERE NAME="CARLA FIVE"
AND EMAIL="LILIAN@UOL.COM";

SELECT * FROM CLIENT;

-- UPDATES PHONES
UPDATE CLIENT
SET PHONE="9823992 - 827382832"
WHERE NAME="JOÃO";

-- GROUP BY
SELECT GENDER, COUNT(*)
FROM CLIENT
GROUP BY GENDER;

INSERT INTO CLIENT VALUES ("CARLA SIX", "F","CLOPES@UOL.COM",29392899,"2938-231","RUA COPPER LEAF - WILLIAMSBURG - KITCHENER");